### ISSUE TITLE
Precisions on jailbreak

### ISSUE THREAD

**Issue by novitae** [doug-leith/cydia#1]
Could you precise in your readme to don't try it with Unco0ver jailbreak ? It completely broke my iPhone jailbreak, I had to reset it completely.

And btw, I was interested to try it because I saw `com.apple.imfoundation.IMRemoteURLConnectionAgent` in [this file](https://github.com/doug-leith/cydia/blob/main/unpin/unpin.plist), is it an exclude list ? I'd like to try to unpin this specific process and I am not finding any solutions ...

**Comment by doug-leith** [comment]
Sorry to hear that.  I've never used unco0ver, just checkra1n.   That file you mention is in the include list i.e. methods in those frameworks/apps will be hooked.  But there's a bit of trial and error involved and some apps take additional defence measures as you probably already know and in that case I suspect it might be necessary to grab to binary and decompile it - if its objective-c it decompiles reasonably nicely.
